name: tamago
description: This project is an anime streaming & manga reader platform.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  
  # Dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0
  
  # Network
  dio: ^5.8.0
  connectivity_plus: ^6.1.4
  json_annotation: ^4.9.0
  
  # Storage
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  
  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.3.1
  
  # Utils
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  dartz: ^0.10.1
  google_sign_in: ^6.2.2
  lucide_icons_flutter: ^3.0.8
  palette_generator: ^0.3.3
  uuid: ^4.5.1
  
  # Supabase
  supabase: ^2.6.0

  # Jikan API
  jikan_api_v4: ^2.2.2
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # WebView
  webview_flutter: ^4.8.0
  omni_video_player: ^2.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mockito: ^5.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lang/
    - .env.dev
    - .env.prod